In [1]:
import numpy as np
a = np.random.rand(5,5)
b = np.random.rand(5,5)
a.shape

(5, 5)

In [2]:
a.size

25

In [3]:
a[2,3]

0.717164142231078

In [4]:
c = a+b
print(c)

array([[0.65668937, 1.44679112, 0.74918151, 1.53235017, 1.09445279],
       [0.54934096, 0.53543809, 1.09733087, 1.10998093, 1.01531029],
       [0.44953624, 0.81475904, 1.72053664, 1.11850836, 1.20637557],
       [1.31666328, 0.75599772, 0.85290334, 0.53184316, 1.68927748],
       [0.91404054, 1.7925    , 0.29303057, 0.96654022, 0.67276462]])

In [5]:
d = a-b
print(d)

array([[-0.0699497 , -0.12533062, -0.42886845, -0.1415441 , -0.36224474],
       [-0.3260418 , -0.07003885,  0.40348661,  0.65844807,  0.30169101],
       [-0.40672054, -0.01250873,  0.21637523,  0.31581993, -0.69373798],
       [ 0.64098562, -0.72092428, -0.08639695,  0.05125075,  0.26199417],
       [ 0.14080595, -0.18400275, -0.17056311,  0.39097504,  0.46933927]])

In [6]:
e = a.dot(b)
print(e)

array([[0.84082678, 1.37221201, 0.93393264, 0.73144472, 1.13509427],
       [1.01699611, 1.77232708, 1.27877082, 0.84913118, 1.57527038],
       [0.93935356, 1.32175523, 1.27635611, 0.74325793, 1.6166749 ],
       [1.00307685, 2.11272065, 1.23394763, 1.32782861, 1.39058972],
       [1.01994099, 1.74897103, 1.08687648, 0.97501521, 1.27176019]])

In [7]:
f = a/b
print(f)

array([[0.80747057, 0.84055864, 0.27190108, 0.83088048, 0.50264934],
       [0.25508746, 0.76864899, 2.16304661, 3.9165012 , 1.84552372],
       [0.05000334, 0.96975892, 1.28770214, 1.78690539, 0.26979313],
       [2.89731188, 0.02374766, 0.81603976, 1.21328157, 1.36712287],
       [1.36419982, 0.81380977, 0.26416984, 2.35857779, 5.61436371]])

In [8]:
g = np.ones((5,5))
g[1:-1,1:-1] = 0
print(g)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
h=np.random.randint(1,100,[5,5])
print(h)

[[15 42 44 67 42]
 [74 66 47 74 70]
 [55 62  3 81 70]
 [50 66 31 86 63]
 [37 58 57 80 32]]


In [11]:
i=(np.amax(h,axis=1))
print(i)

[67 74 81 86 80]


In [12]:
j=((np.amin(h,axis=1)))
print(j)

[15 47  3 31 32]


In [14]:
k=np.max(i)
l=np.min(j)
print(k)
print(l)

86
3


In [15]:
m=(h-l)/(k-l)
print(m)

[[0.14457831 0.46987952 0.4939759  0.77108434 0.46987952]
 [0.85542169 0.75903614 0.53012048 0.85542169 0.80722892]
 [0.62650602 0.71084337 0.         0.93975904 0.80722892]
 [0.56626506 0.75903614 0.3373494  1.         0.72289157]
 [0.40963855 0.6626506  0.65060241 0.92771084 0.34939759]]


In [2]:
import numpy as np
array1 = np.arange(16).reshape(4,4)
print(array1)
list1 = array1.tolist()
print(list1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]
