In [12]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


def load_data():
    iris = datasets.load_iris()
    print(iris.keys())
    n_samples, n_features = iris.data.shape
    print((n_samples, n_features))
    print(iris.data[0])
    #print(iris.target.shape)
    print(iris.target)#目标值
    print("target_names:",iris.target_names)
    #print("feature_names:",iris.feature_names)#特征名称
    
def main():
    load_data()

if __name__ == '__main__':
    main()


dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])
(150, 4)
[5.1 3.5 1.4 0.2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
target_names: ['setosa' 'versicolor' 'virginica']


In [11]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


def load_data():
    # 共150条数据，训练120条，测试30条，进行2,8分进行模型训练
    # 每条数据类型为 x{nbarray} [6.4, 3.1, 5.5, 1.8]
    inputdata = datasets.load_iris()
    # 切分，测试训练2,8分
    x_train, x_test, y_train, y_test = train_test_split(inputdata.data, inputdata.target, test_size = 0.2, random_state = 0)
    return x_train, x_test, y_train, y_test

def main():
    #读取数据，并显示数据格式
    load_data()
    # 训练集x ,测试集x,训练集label,测试集label
    x_train, x_test, y_train, y_test = prediction_data()
    # l2为正则项
    model = LogisticRegression(penalty = 'l2')
    model.fit(x_train, y_train)

    print("w: ", model.coef_)
    print("b: ", model.intercept_)
    # 准确率
    print("precision: ", model.score(x_test, y_test))
    print("MSE: ", np.mean((model.predict(x_test) - y_test) ** 2))
    
if __name__ == '__main__':
    main()

w:  [[ 0.41682398  1.34687247 -2.15760284 -0.98058923]
 [ 0.22719571 -1.32234908  0.58097932 -1.25562927]
 [-1.559254   -1.34663487  2.2897358   2.25775566]]
b:  [ 0.24822199  1.07209792 -1.15180528]
precision:  0.9666666666666667
MSE:  0.03333333333333333
