In [3]:
import numpy.matlib
import numpy as np
a = np.matlib.rand(5,5)
print(a)
print("size:",a.size)
print("shape:",a.shape)
print('矩阵取一行:',a[0])
print('矩阵取一列:',a[:,1])

[[0.39017779 0.38680914 0.23173568 0.3206731  0.38565798]
 [0.05951755 0.04398937 0.59163567 0.85007467 0.93991994]
 [0.0654059  0.82260195 0.85449231 0.9272378  0.73396666]
 [0.8960463  0.72395629 0.4707016  0.24418392 0.86017986]
 [0.72285951 0.48526053 0.22908274 0.17349619 0.08396595]]
size: 25
shape: (5, 5)
矩阵取一行: [[0.39017779 0.38680914 0.23173568 0.3206731  0.38565798]]
矩阵取一列: [[0.38680914]
 [0.04398937]
 [0.82260195]
 [0.72395629]
 [0.48526053]]


In [17]:
import numpy as np
a = np.empty([2,2])
b = np.empty([2,2])
print ('乘:',np.dot(a,b))
print ('除:',a / b)
print('加:',a + b)
print('减:',a - b)


乘: [[0.79470772 1.31320069]
 [1.12440799 1.85509525]]
除: [[ 1.0224207   2.47115602]
 [ 2.50798054 10.98203437]]
加: [[1.11302322 3.18051825]
 [0.75146949 4.2209429 ]]
减: [[0.01233906 1.34797703]
 [0.32303525 3.51639762]]


In [5]:
##########
import numpy as np
a = np.empty([5,5])
print(a)
amax,amin = a.max(axis=0),a.min(axis=0)
a=(a-amin)/(amax-amin)
print("数据标准化：\n",a)

###########创建二维数组 边界值为1##############
#创建二维数组，边界为1，中间为0
c = np.ones((5,5))
c[1:-1,1:-1] = 0
print('矩阵c:\n{}'.format(c))


[[0.39527659 0.4402957  0.00424192 0.19526176 0.35246291]
 [0.         0.         0.5797048  0.89762655 1.        ]
 [0.00703903 1.         1.         1.         0.75938744]
 [1.         0.87330585 0.38633699 0.09378244 0.90684069]
 [0.79296972 0.56674034 0.         0.         0.        ]]
数据标准化：
 [[0.39527659 0.4402957  0.00424192 0.19526176 0.35246291]
 [0.         0.         0.5797048  0.89762655 1.        ]
 [0.00703903 1.         1.         1.         0.75938744]
 [1.         0.87330585 0.38633699 0.09378244 0.90684069]
 [0.79296972 0.56674034 0.         0.         0.        ]]
矩阵c:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
import numpy as np
a = [1,2,3,4,5]
type(a)
b = np.array(a)
type(b)




numpy.ndarray

In [40]:
import numpy as np
array_1 = np.random.randint(1,50,10)
print(array_1)
array_2 = array_1.reshape(2,5)
print(array_2)

[37 29 31  1 46 10 13 47  2 34]
[[37 29 31  1 46]
 [10 13 47  2 34]]


In [72]:
import pandas as pd
import numpy as np
import os
os.getcwd()
df = pd.DataFrame(pd.read_csv('hancheng.csv'))
print(df.head(3))         ###head
#print(df.describe)       ###describe
print(df.shape)           ###shape
      
def f(x):
      return x - 1
df['年龄'] = df['年龄'].apply(f)
print(df)



   school   姓名 性别          生日  年龄    裸右   裸左 带镜右眼 带镜左眼  电脑验光右      ...       \
0  junior  张熙涵  男   2000/3/25  18  0.08  1.0  NaN  NaN    NaN      ...        
1  junior   郭鑫  男  1999/12/22  18  0.20  0.1  0.5  0.1  -3.25      ...        
2  junior  郭佳宝  男   1999/8/27  18  1.00  0.3  NaN  NaN    NaN      ...        

  Unnamed: 233 Unnamed: 234 Unnamed: 235 Unnamed: 236  Unnamed: 237  \
0          NaN          NaN          NaN          NaN           NaN   
1          NaN          NaN          NaN          NaN           NaN   
2          NaN          NaN          NaN          NaN           NaN   

   Unnamed: 238  Unnamed: 239  Unnamed: 240  Unnamed: 241  Unnamed: 242  
0           NaN           NaN           NaN           NaN           NaN  
1           NaN           NaN           NaN           NaN           NaN  
2           NaN           NaN           NaN           NaN           NaN  

[3 rows x 243 columns]
(1461, 243)


TypeError: unsupported operand type(s) for -: 'str' and 'int'

In [24]:
# 索引 切片 删除 merge
import pandas as pd
df = pd.DataFrame({"id":[1001,1002,1003,1004,1005,1006], 
 "date":pd.date_range('20130102', periods=6),
  "city":['Beijing ', 'SH', ' guangzhou ', 'Shenzhen', 'shanghai', 'Beijing '],
 "age":[23,44,54,32,34,32],
 "category":['100-A','100-B','110-A','110-C','210-A','130-F'],
  "price":[1200,np.nan,2133,5433,np.nan,4432]},
  columns =['id','date','city','category','age','price'])
print(df)

print(df['id'])                  ###设置索引列

print(df.iloc[2:4,2:4])            ###切片：选取第三行第四行与第三列第四列之间的数据

df_2 = df.drop(['id'],axis = 1 )     ###删除：删除id列
print(df_2)

def format_name(s):    ### map: city属性按首字母大写 后续字母小写的规则
    s1 = s[0:1].upper() + s[1:].lower();
    return s1
df['city']= df['city'].map(format_name)
print(df)

df1=pd.DataFrame({"id":[1001,1002,1003,1004,1005,1006,1007,1008], ###merge 并集
"gender":['male','female','male','female','male','female','male','female'],
"pay":['Y','N','Y','Y','N','Y','N','Y',],
"m-point":[10,12,20,40,40,40,30,20]})
df_outer=pd.merge(df,df1,how='outer')
print("merge:\n",df_outer)

     id       date         city category  age   price
0  1001 2013-01-02     Beijing     100-A   23  1200.0
1  1002 2013-01-03           SH    100-B   44     NaN
2  1003 2013-01-04   guangzhou     110-A   54  2133.0
3  1004 2013-01-05     Shenzhen    110-C   32  5433.0
4  1005 2013-01-06     shanghai    210-A   34     NaN
5  1006 2013-01-07     Beijing     130-F   32  4432.0
0    1001
1    1002
2    1003
3    1004
4    1005
5    1006
Name: id, dtype: int64
          city category
2   guangzhou     110-A
3     Shenzhen    110-C
        date         city category  age   price
0 2013-01-02     Beijing     100-A   23  1200.0
1 2013-01-03           SH    100-B   44     NaN
2 2013-01-04   guangzhou     110-A   54  2133.0
3 2013-01-05     Shenzhen    110-C   32  5433.0
4 2013-01-06     shanghai    210-A   34     NaN
5 2013-01-07     Beijing     130-F   32  4432.0
     id       date         city category  age   price
0  1001 2013-01-02     Beijing     100-A   23  1200.0
1  1002 2013-01-03     

In [ ]:
# import datetime
now = datetime.datetime.now()
now
now.day,now.month,now.year

In [ ]:
# contact
from numpy.random import rand
import numpy as np


df_1=pd.DataFrame({'Weather':['cold','hot','cold','hot','cold','hot','cold'],'Food':['soup','soup','icecream','chocolate','icecream','icecream','soup'],
                'Price':10*rand(7)})
print(df_1)
print ("Contact  together:\n",pd.concat([df_1,df_1[:3]]))