# numpy

In [1]:
import numpy as np

#构造矩阵a
a = np.arange(25).reshape(5,5)
print('矩阵a:\n{}'.format(a))
print('size: ',a.size)
print('shape: ',a.shape)
print('矩阵a第三列：',a[0:5,2])
print('矩阵a第二行：',a[1,:])
print('***********************************')

#构造矩阵b
b = np.array((1,2,3,4,5))
print('矩阵b:\n{}'.format(b))
print('***********************************')

#矩阵a和b的四则运算
print('a+b:\n{}'.format(a + b))
print('***********************************')
print('a-b:\n{}'.format(a - b))
print('***********************************')
print('a*b:\n{}'.format(a * b))
print('***********************************')
print('a/b:\n{}'.format(a / b))
print('***********************************')

#创建二维数组，边界为1，中间为0
c = np.ones((5,5))
c[1:-1,1:-1] = 0
print('矩阵c:\n{}'.format(c))

矩阵a:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
size:  25
shape:  (5, 5)
矩阵a第三列： [ 2  7 12 17 22]
矩阵a第二行： [5 6 7 8 9]
***********************************
矩阵b:
[1 2 3 4 5]
***********************************
a+b:
[[ 1  3  5  7  9]
 [ 6  8 10 12 14]
 [11 13 15 17 19]
 [16 18 20 22 24]
 [21 23 25 27 29]]
***********************************
a-b:
[[-1 -1 -1 -1 -1]
 [ 4  4  4  4  4]
 [ 9  9  9  9  9]
 [14 14 14 14 14]
 [19 19 19 19 19]]
***********************************
a*b:
[[  0   2   6  12  20]
 [  5  12  21  32  45]
 [ 10  22  36  52  70]
 [ 15  32  51  72  95]
 [ 20  42  66  92 120]]
***********************************
a/b:
[[ 0.          0.5         0.66666667  0.75        0.8       ]
 [ 5.          3.          2.33333333  2.          1.8       ]
 [10.          5.5         4.          3.25        2.8       ]
 [15.          8.          5.66666667  4.5         3.8       ]
 [20.         10.5         7.33333333  5.75        4.8       ]]
***

# numpy 构造随机矩阵 进行归一化处理

In [4]:
import numpy as np
d = np.random.random((5,5))
print('原始矩阵d:\n{}'.format(d))
print('*****************************************************************')
d_max = d.max()
d_min = d.min()
d_arr = (d - d_min) / (d_max - d_min)
print('归一化矩阵d_arr:\n{}'.format(d_arr))

原始矩阵d:
[[0.96435315 0.65146305 0.38291574 0.28890781 0.54989035]
 [0.33377524 0.87886745 0.79575847 0.94822392 0.48648104]
 [0.45749504 0.46682743 0.45137282 0.78163275 0.86057496]
 [0.8343858  0.45723036 0.46739443 0.69293637 0.77130386]
 [0.83689795 0.26272211 0.09931389 0.40811098 0.44542127]]
*****************************************************************
归一化矩阵d_arr:
[[1.         0.63829376 0.32784853 0.21917377 0.520874  ]
 [0.27104128 0.90117709 0.80510171 0.98135434 0.44757177]
 [0.41406346 0.42485186 0.40698607 0.78877213 0.88003067]
 [0.84975554 0.41375749 0.42550733 0.68623762 0.77683176]
 [0.85265964 0.18890267 0.         0.35697465 0.40010598]]


# list to array

In [6]:
import numpy as np
#构造数组
e_array = np.arange(15).reshape(3,5)
print('数组e_array:\n{}'.format(e_array))
print('***********************************')
e_list = e_array.tolist()
print('列表e_list:\n{}'.format(e_list))

数组e_array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
***********************************
列表e_list:
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


In [7]:
import numpy as np

e_array = np.array((1,2,3,4,5))
print(e_array)

e_list = e_array.tolist()
print(e_list)

[1 2 3 4 5]
[1, 2, 3, 4, 5]
