# numpy

In [27]:
import numpy as np

m = np.random.rand(5, 5)
print(m)

print(m.size)
print(m.shape)

print(m[:, 1])
print(m[1, :])

[[0.22018383 0.93104343 0.07498792 0.05050736 0.91889973]
 [0.48689807 0.08732359 0.2365455  0.42906093 0.39754308]
 [0.5476248  0.58899648 0.56220747 0.05751027 0.44611702]
 [0.98711044 0.65557727 0.80513271 0.63378551 0.94427038]
 [0.77256238 0.65484543 0.40801577 0.91728761 0.84663198]]
25
(5, 5)
[0.93104343 0.08732359 0.58899648 0.65557727 0.65484543]
[0.48689807 0.08732359 0.2365455  0.42906093 0.39754308]


In [28]:
n = np.random.rand(5, 5)
print(n)
print(m + n)
print(m - n)
print(m * n)
print(m / n)

[[0.34210612 0.90210693 0.94641614 0.43925436 0.91387824]
 [0.07819672 0.23650315 0.59465089 0.18928137 0.68580919]
 [0.52220373 0.27932121 0.56211748 0.20568619 0.49484806]
 [0.03922047 0.42685307 0.22289237 0.1050435  0.09954508]
 [0.76170008 0.95749938 0.97392116 0.19860738 0.23658193]]
[[0.56228995 1.83315037 1.02140406 0.48976172 1.83277797]
 [0.56509479 0.32382674 0.83119639 0.6183423  1.08335227]
 [1.06982853 0.86831769 1.12432495 0.26319646 0.94096509]
 [1.02633091 1.08243034 1.02802509 0.73882901 1.04381546]
 [1.53426247 1.61234481 1.38193694 1.11589499 1.08321391]]
[[-1.21922294e-01  2.89364997e-02 -8.71428225e-01 -3.88746997e-01
   5.02149135e-03]
 [ 4.08701358e-01 -1.49179555e-01 -3.58105393e-01  2.39779567e-01
  -2.88266105e-01]
 [ 2.54210679e-02  3.09675268e-01  8.99835767e-05 -1.48175919e-01
  -4.87310383e-02]
 [ 9.47889963e-01  2.28724200e-01  5.82240339e-01  5.28742003e-01
   8.44725297e-01]
 [ 1.08622993e-02 -3.02653950e-01 -5.65905390e-01  7.18680230e-01
   6.1005005

In [29]:
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
p = (m - np.min(m)) / np.max(m) - np.min(m)
print(p)

print(np.array(m))

[[ 0.12138472  0.84152664 -0.02570714 -0.05050736  0.82922437]
 [ 0.39158169 -0.01321039  0.13796004  0.33298932  0.30105991]
 [ 0.45310137  0.49501328  0.46787446 -0.04341301  0.35026812]
 [ 0.89832576  0.56246348  0.71397179  0.54038716  0.8549263 ]
 [ 0.68097616  0.56172208  0.31166935  0.8275912   0.75601296]]
[[0.22018383 0.93104343 0.07498792 0.05050736 0.91889973]
 [0.48689807 0.08732359 0.2365455  0.42906093 0.39754308]
 [0.5476248  0.58899648 0.56220747 0.05751027 0.44611702]
 [0.98711044 0.65557727 0.80513271 0.63378551 0.94427038]
 [0.77256238 0.65484543 0.40801577 0.91728761 0.84663198]]


In [31]:
s = np.reshape(n,(1,25))
print(s)

[[0.34210612 0.90210693 0.94641614 0.43925436 0.91387824 0.07819672
  0.23650315 0.59465089 0.18928137 0.68580919 0.52220373 0.27932121
  0.56211748 0.20568619 0.49484806 0.03922047 0.42685307 0.22289237
  0.1050435  0.09954508 0.76170008 0.95749938 0.97392116 0.19860738
  0.23658193]]


# pandas

In [32]:
import pandas as pd
import numpy as np
import datetime


CSV_FILE_PATH = 'C:/Users/lenovo/Desktop/csj/hanchen.csv'
df = pd.read_csv(CSV_FILE_PATH)
print(df.head(2))#前2行
print(df.tail(2))#最后两行
print(df.shape)


#df1 = pd.read_csv('hanchen.csv')[0:10]
#print(df1)

#d = df[df.'年龄'.isin([17])]#选择
#print(d.head(2))
#q = df[~df['年龄'].isin([19])]#删除
#print(q.head(2))

   school   姓名 性别          生日  年龄    裸右   裸左 带镜右眼 带镜左眼  电脑验光右      ...       \
0  junior  张熙涵  男   2000/3/25  18  0.08  1.0  NaN  NaN    NaN      ...        
1  junior   郭鑫  男  1999/12/22  18  0.20  0.1  0.5  0.1  -3.25      ...        

  Unnamed: 233 Unnamed: 234 Unnamed: 235 Unnamed: 236  Unnamed: 237  \
0          NaN          NaN          NaN          NaN           NaN   
1          NaN          NaN          NaN          NaN           NaN   

   Unnamed: 238  Unnamed: 239  Unnamed: 240  Unnamed: 241  Unnamed: 242  
0           NaN           NaN           NaN           NaN           NaN  
1           NaN           NaN           NaN           NaN           NaN  

[2 rows x 243 columns]
      school   姓名 性别          生日  年龄   裸右    裸左 带镜右眼 带镜左眼 电脑验光右      ...       \
1459  senior  元秦峰  男   1998/9/10  19  0.2  0.25    1    1   NaN      ...        
1460  senior   刘华  男  1996/10/23  17  0.6  0.50   缺失   缺失  -1.5      ...        

     Unnamed: 233 Unnamed: 234 Unnamed: 235 Unnamed: 236  

In [33]:
df.describe()

df = df.set_index('生日')# 将生日设置为index

df = pd.DataFrame({'裸左':[1,2,1,2], '裸右':[3,4,5,6]})
print(df.groupby('裸左').apply(sum))


    裸左  裸右
裸左        
1    2   8
2    4  10


In [34]:
pd.DataFrame(df, columns = ['school', '姓名', '生日', '年龄'])
pd.DataFrame(df, index = [1, 4])
df['裸左'] > 0.4
df.iloc[[1,3], 2:4]
df[df['裸左'] > 0.5]

裸左  裸右
0   1   3
1   2   4
2   1   5
3   2   6

In [35]:
df1 = pd.DataFrame({'key':['b','b','a','c','a'],'data1':range(5)})
df2 = pd.DataFrame({'key':['b','f','d','c','a'],'data2':range(5)})
df3 = pd.merge(df1,df2,on = 'key')
print(df1)
print(df2)
print(df3)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
  key  data2
0   b      0
1   f      1
2   d      2
3   c      3
4   a      4
  key  data1  data2
0   b      0      0
1   b      1      0
2   a      2      4
3   a      4      4
4   c      3      3


In [36]:
f = [df1,df2]
df4 = pd.concat(f)
print(df4)

   data1  data2 key
0    0.0    NaN   b
1    1.0    NaN   b
2    2.0    NaN   a
3    3.0    NaN   c
4    4.0    NaN   a
0    NaN    0.0   b
1    NaN    1.0   f
2    NaN    2.0   d
3    NaN    3.0   c
4    NaN    4.0   a


D:\python3.7\Anaconda\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


In [43]:
#dateparse = lambda dates : pd.datetime.strptime(dates,'%d/%m/%Y%H:%M')
#rawdata = pd.read_csv('C:/Users/lenovo/Desktop/csj/hanchen.csv',parse_dates={'timeline':['生日']},date_parser=dateparse)

df.to_csv('C:/Users/lenovo/Desktop/csj/a.csv')